repo_path: "./DizipalV2"
dizipal_path: "src/main/kotlin/com/Prueba/DizipalV2.kt"
gradle_path: "build.gradle.kts"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"