name: Check Dizipal URL

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-url:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run URL checker
      id: url-check
      run: |
        python src/main/kotlin/com/Prueba/bakalim.py
      
    - name: Configure Git
      if: steps.url-check.outputs.url_updated == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Commit and push changes
      if: steps.url-check.outputs.url_updated == 'true'
      run: |
        git add src/main/kotlin/com/Prueba/DizipalV2.kt build.gradle.kts
        git commit -m "Update Dizipal URL to ${{ steps.url-check.outputs.new_url }} and increment version"
        git push
