name: URL Kontrolü ve Güncelleme

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu kontrol et
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY.GITHUB_TOKEN }}
          
      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Bağımlılıkları yükle
        run: pip install requests
          
      - name: Git kullanıcı bilgilerini ayarla
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
      - name: URL kontrol ve güncelleme betiğini çalıştır
        run: python url_checker.py --file "DizipalV2.kt" --dir "./DizipalV2"

